


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."Email verifiyer status" AS ENUM (
    'valid',
    'invalid',
    'unknown'
);


ALTER TYPE "public"."Email verifiyer status" OWNER TO "postgres";


COMMENT ON TYPE "public"."Email verifiyer status" IS 'Status after being thrown in the email verifiyer function';



CREATE TYPE "public"."Event status" AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'DELETED',
    'PAST',
    'CANCELLED',
    'SOLDOUT'
);


ALTER TYPE "public"."Event status" OWNER TO "postgres";


CREATE TYPE "public"."general_status" AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'DELETED'
);


ALTER TYPE "public"."general_status" OWNER TO "postgres";


CREATE TYPE "public"."pictures_status" AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'DELETED'
);


ALTER TYPE "public"."pictures_status" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."clean_inactive_users"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  IF NOT NEW.is_cleanup THEN
    DELETE FROM online_users
    WHERE last_seen < NOW() - INTERVAL '1 minute' AND NOT is_cleanup;
  END IF;
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."clean_inactive_users"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_realtime_identifier"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO '', 'public'
    AS $$
BEGIN
  -- Insert a new row into realtime_values with the FK reference
  INSERT INTO public.realtime_values (identifier_id, created_at)
  VALUES (NEW.id, NOW());

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_realtime_identifier"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."increment_click_count"("row_id" integer, "step" integer) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  update section_click
  set count = count + step
  where id = row_id;
end;
$$;


ALTER FUNCTION "public"."increment_click_count"("row_id" integer, "step" integer) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."clicks_paliers" (
    "id" bigint NOT NULL,
    "name" "text" DEFAULT 'Coming soon..'::"text",
    "target" bigint DEFAULT '0'::bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."clicks_paliers" OWNER TO "postgres";


ALTER TABLE "public"."clicks_paliers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clicks_paliers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."section_events" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "price" bigint NOT NULL,
    "date" timestamp with time zone NOT NULL,
    "place" "text" NOT NULL,
    "link" "text",
    "img" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "public"."Event status" DEFAULT 'ACTIVE'::"public"."Event status" NOT NULL
);


ALTER TABLE "public"."section_events" OWNER TO "postgres";


COMMENT ON TABLE "public"."section_events" IS 'List of events';



ALTER TABLE "public"."section_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."global_variables" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "value" "text" NOT NULL
);


ALTER TABLE "public"."global_variables" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."global_variables_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."global_variables_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."global_variables_id_seq" OWNED BY "public"."global_variables"."id";



CREATE TABLE IF NOT EXISTS "public"."merch_categories" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "order" integer DEFAULT 0
);


ALTER TABLE "public"."merch_categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."merch_categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."merch_categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."merch_categories_id_seq" OWNED BY "public"."merch_categories"."id";



CREATE TABLE IF NOT EXISTS "public"."merch_items" (
    "id" bigint NOT NULL,
    "name" "text",
    "description" "text",
    "price" bigint,
    "tags" "text"[],
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "stripe_paylink" "text" DEFAULT ''::"text" NOT NULL,
    "image_url" "text",
    "out_of_stock" boolean DEFAULT false NOT NULL,
    "status" "public"."general_status" DEFAULT 'INACTIVE'::"public"."general_status" NOT NULL,
    "category" bigint
);


ALTER TABLE "public"."merch_items" OWNER TO "postgres";


COMMENT ON COLUMN "public"."merch_items"."image_url" IS 'URL to the merch item image stored in storage bucket';



ALTER TABLE "public"."merch_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."merch_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."music_player" (
    "id" bigint NOT NULL,
    "audio_link" "text",
    "cover_link" "text",
    "title" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."music_player" OWNER TO "postgres";


ALTER TABLE "public"."music_player" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."music_player_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."online_users" (
    "client_id" "uuid" NOT NULL,
    "last_seen" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_cleanup" boolean DEFAULT false
);


ALTER TABLE "public"."online_users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."section_pictures" (
    "id" bigint NOT NULL,
    "title" character varying,
    "storage_ref" "text",
    "date" "date",
    "place" character varying,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "status" "public"."general_status" DEFAULT 'ACTIVE'::"public"."general_status" NOT NULL
);


ALTER TABLE "public"."section_pictures" OWNER TO "postgres";


ALTER TABLE "public"."section_pictures" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pictures_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."realtime_identifiers" (
    "id" bigint NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."realtime_identifiers" OWNER TO "postgres";


ALTER TABLE "public"."realtime_identifiers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."realtime_identifiers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."realtime_values" (
    "id" bigint NOT NULL,
    "identifier_id" bigint,
    "value" bigint DEFAULT '0'::bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."realtime_values" OWNER TO "postgres";


ALTER TABLE "public"."realtime_values" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."realtime_values_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."section_click" (
    "id" bigint NOT NULL,
    "count" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."section_click" OWNER TO "postgres";


ALTER TABLE "public"."section_click" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."section_click_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."section_spotlight" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "subtitle" "text",
    "buy_link" "text",
    "listen_link" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "status" "text" DEFAULT 'ACTIVE'::"text"
);


ALTER TABLE "public"."section_spotlight" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."section_videos" (
    "id" bigint NOT NULL,
    "description" "text",
    "url" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "order" integer,
    "status" "public"."general_status" DEFAULT 'ACTIVE'::"public"."general_status" NOT NULL
);


ALTER TABLE "public"."section_videos" OWNER TO "postgres";


ALTER TABLE "public"."section_videos" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."section_videos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."section_spotlight" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."spotlight_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."global_variables" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."global_variables_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."merch_categories" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."merch_categories_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."clicks_paliers"
    ADD CONSTRAINT "clicks_paliers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."section_events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."global_variables"
    ADD CONSTRAINT "global_variables_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."global_variables"
    ADD CONSTRAINT "global_variables_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."merch_categories"
    ADD CONSTRAINT "merch_categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."merch_items"
    ADD CONSTRAINT "merch_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."music_player"
    ADD CONSTRAINT "music_player_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."online_users"
    ADD CONSTRAINT "online_users_pkey" PRIMARY KEY ("client_id");



ALTER TABLE ONLY "public"."section_pictures"
    ADD CONSTRAINT "pictures_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."realtime_identifiers"
    ADD CONSTRAINT "realtime_identifiers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."realtime_values"
    ADD CONSTRAINT "realtime_values_identifier_id_key" UNIQUE ("identifier_id");



ALTER TABLE ONLY "public"."realtime_values"
    ADD CONSTRAINT "realtime_values_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."section_click"
    ADD CONSTRAINT "section_click_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."section_videos"
    ADD CONSTRAINT "section_videos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."section_spotlight"
    ADD CONSTRAINT "spotlight_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."section_spotlight"
    ADD CONSTRAINT "spotlight_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "clean_inactive_users_trigger" AFTER INSERT OR UPDATE ON "public"."online_users" FOR EACH ROW EXECUTE FUNCTION "public"."clean_inactive_users"();



CREATE OR REPLACE TRIGGER "on_new_realtime_identifier_insert" AFTER INSERT ON "public"."realtime_identifiers" FOR EACH ROW EXECUTE FUNCTION "public"."handle_new_realtime_identifier"();



ALTER TABLE ONLY "public"."merch_items"
    ADD CONSTRAINT "merch_items_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."merch_categories"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."realtime_values"
    ADD CONSTRAINT "realtime_values_identifier_id_fkey" FOREIGN KEY ("identifier_id") REFERENCES "public"."realtime_identifiers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Allow delete for authenticated" ON "public"."section_videos" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Allow delete to authenticated users" ON "public"."global_variables" FOR DELETE USING (("auth"."role"() IS NOT NULL));



CREATE POLICY "Allow insert for authenticated" ON "public"."merch_categories" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow insert for authenticated" ON "public"."section_videos" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow insert to authenticated users" ON "public"."global_variables" FOR INSERT WITH CHECK (("auth"."role"() IS NOT NULL));



CREATE POLICY "Allow read access to all users" ON "public"."global_variables" FOR SELECT USING (true);



CREATE POLICY "Allow select for all users" ON "public"."merch_items" FOR SELECT USING (true);



CREATE POLICY "Allow select for anon" ON "public"."merch_categories" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow select for anon" ON "public"."section_videos" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Allow update for authenticated" ON "public"."merch_categories" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow update for authenticated" ON "public"."section_videos" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Allow update to authenticated users" ON "public"."global_variables" FOR UPDATE USING (("auth"."role"() IS NOT NULL));



CREATE POLICY "Enable all ops for authenticated users only" ON "public"."section_events" TO "authenticated" USING (true);



CREATE POLICY "Enable delete for authenticated users only" ON "public"."merch_items" FOR DELETE TO "authenticated" USING (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."clicks_paliers" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."merch_items" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."section_pictures" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."section_spotlight" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access" ON "public"."clicks_paliers" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Enable read access" ON "public"."section_click" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."merch_items" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."online_users" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."realtime_values" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."section_pictures" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."section_spotlight" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Enable read access for anon and auth" ON "public"."music_player" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Enable update for authenticated and anon" ON "public"."realtime_values" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Enable update for authenticated users only" ON "public"."clicks_paliers" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Select for anon" ON "public"."section_events" FOR SELECT TO "authenticated", "anon" USING (true);



CREATE POLICY "Update click count" ON "public"."section_click" FOR UPDATE TO "authenticated", "anon" USING (true);



CREATE POLICY "Update for auth" ON "public"."section_pictures" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "Update for authenticated users" ON "public"."section_spotlight" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "all for service role" ON "public"."online_users" TO "service_role" USING (true);



ALTER TABLE "public"."clicks_paliers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."global_variables" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."merch_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."merch_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."music_player" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."online_users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."realtime_identifiers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."realtime_values" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."section_click" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."section_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."section_pictures" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."section_spotlight" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."section_videos" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update for authenticated users only" ON "public"."merch_items" FOR UPDATE TO "authenticated" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."online_users";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."section_click";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."clean_inactive_users"() TO "anon";
GRANT ALL ON FUNCTION "public"."clean_inactive_users"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."clean_inactive_users"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_realtime_identifier"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_realtime_identifier"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_realtime_identifier"() TO "service_role";



GRANT ALL ON FUNCTION "public"."increment_click_count"("row_id" integer, "step" integer) TO "anon";
GRANT ALL ON FUNCTION "public"."increment_click_count"("row_id" integer, "step" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_click_count"("row_id" integer, "step" integer) TO "service_role";


















GRANT ALL ON TABLE "public"."clicks_paliers" TO "anon";
GRANT ALL ON TABLE "public"."clicks_paliers" TO "authenticated";
GRANT ALL ON TABLE "public"."clicks_paliers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."clicks_paliers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clicks_paliers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clicks_paliers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."section_events" TO "anon";
GRANT ALL ON TABLE "public"."section_events" TO "authenticated";
GRANT ALL ON TABLE "public"."section_events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."global_variables" TO "anon";
GRANT ALL ON TABLE "public"."global_variables" TO "authenticated";
GRANT ALL ON TABLE "public"."global_variables" TO "service_role";



GRANT ALL ON SEQUENCE "public"."global_variables_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."global_variables_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."global_variables_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."merch_categories" TO "anon";
GRANT ALL ON TABLE "public"."merch_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."merch_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."merch_categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."merch_categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."merch_categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."merch_items" TO "anon";
GRANT ALL ON TABLE "public"."merch_items" TO "authenticated";
GRANT ALL ON TABLE "public"."merch_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."merch_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."merch_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."merch_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."music_player" TO "anon";
GRANT ALL ON TABLE "public"."music_player" TO "authenticated";
GRANT ALL ON TABLE "public"."music_player" TO "service_role";



GRANT ALL ON SEQUENCE "public"."music_player_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."music_player_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."music_player_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."online_users" TO "anon";
GRANT ALL ON TABLE "public"."online_users" TO "authenticated";
GRANT ALL ON TABLE "public"."online_users" TO "service_role";



GRANT ALL ON TABLE "public"."section_pictures" TO "anon";
GRANT ALL ON TABLE "public"."section_pictures" TO "authenticated";
GRANT ALL ON TABLE "public"."section_pictures" TO "service_role";



GRANT ALL ON SEQUENCE "public"."pictures_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pictures_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pictures_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."realtime_identifiers" TO "anon";
GRANT ALL ON TABLE "public"."realtime_identifiers" TO "authenticated";
GRANT ALL ON TABLE "public"."realtime_identifiers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."realtime_identifiers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."realtime_identifiers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."realtime_identifiers_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."realtime_values" TO "anon";
GRANT ALL ON TABLE "public"."realtime_values" TO "authenticated";
GRANT ALL ON TABLE "public"."realtime_values" TO "service_role";



GRANT ALL ON SEQUENCE "public"."realtime_values_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."realtime_values_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."realtime_values_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."section_click" TO "anon";
GRANT ALL ON TABLE "public"."section_click" TO "authenticated";
GRANT ALL ON TABLE "public"."section_click" TO "service_role";



GRANT ALL ON SEQUENCE "public"."section_click_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."section_click_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."section_click_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."section_spotlight" TO "anon";
GRANT ALL ON TABLE "public"."section_spotlight" TO "authenticated";
GRANT ALL ON TABLE "public"."section_spotlight" TO "service_role";



GRANT ALL ON TABLE "public"."section_videos" TO "anon";
GRANT ALL ON TABLE "public"."section_videos" TO "authenticated";
GRANT ALL ON TABLE "public"."section_videos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."section_videos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."section_videos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."section_videos_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."spotlight_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."spotlight_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."spotlight_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































